version: '3.7'

services:
  nginx:
    image: nginx
    ports:
      - 443:443
    depends_on:
      - wso2is10
      - wso2is11
    volumes:
      - ./nginx/:/etc/nginx/
    networks: 
      - wso2cluster
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 2m30s
      restart_policy:
        condition: on-failure

  wso2is10:
    image: identityorg/wso2is58:1.1
    depends_on:
      - mysql
    volumes:
#      - repository:/home/wso2carbon/wso2is-5.8.0/repository/
      - tenants:/home/wso2carbon/wso2is-5.8.0/tenants/
#      - ./axis-cluster/axis2-10.xml:/home/wso2carbon/wso2is-5.8.0/repository/conf/axis2/axis2.xml
    networks: 
      - wso2cluster
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 1m30s
      restart_policy:
        condition: on-failure

  wso2is11:
    image: identityorg/wso2is58:1.1
    depends_on:
      - mysql
    volumes:
#      - repository:/home/wso2carbon/wso2is-5.8.0/repository/
      - tenants:/home/wso2carbon/wso2is-5.8.0/tenants/
#      - ./axis-cluster/axis2-11.xml:/home/wso2carbon/wso2is-5.8.0/repository/conf/axis2/axis2.xml
    networks: 
      - wso2cluster
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 1m30s
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:5
    networks:
      - wso2cluster
    ports:
       - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
      - mysqldata:/var/lib/mysql/

volumes:
#  repository:
  mysqldata:
  tenants:

networks:
  wso2cluster:
    ipam: 
      driver: default
      config:
        - subnet: 172.28.5.0/24
